# Generated by Django 3.1.3 on 2021-01-15 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi_berita', models.TextField()),
                ('gambar', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('trending', models.CharField(blank=True, max_length=80)),
                ('waktu_posting', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 15, 20, 59, 7, 897427))),
            ],
        ),
    ]
