# Generated by Django 3.1.3 on 2021-02-16 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('gambar', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('waktu_posting', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ketuaUmum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi_berita', models.TextField()),
                ('gambar', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('waktu_posting', models.CharField(blank=True, max_length=100)),
                ('tags', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='berita',
            name='waktu_posting',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 16, 18, 6, 22, 67312)),
        ),
    ]
