# Generated by Django 3.1.3 on 2021-01-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='waktu_daftar',
            field=models.CharField(default=(), max_length=60),
            preserve_default=False,
        ),
    ]
